spring.application.name=reservas-api
server.port=8080
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

logging.level.com.aa.reservas=INFO
logging.file.name=logs/reservas-api.log

springdoc.swagger-ui.path=/swagger-ui.html
