spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/reservas_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:reservas_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:reservas_pass}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.com.aa.reservas=${APP_LOG_LEVEL:INFO}
